name: auto-repository
on:
  workflow_dispatch:
    inputs:
      repository-name:
        required: true
        description: "레포지토리 input값 입력"

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository
        id: create-repo
        run: |
          if gh repo create gpturtle-cicd-project/${{inputs.repository-name}}-action-repo --public --add-readme; then
            echo "success=true" >> "$GITHUB_OUTPUT"
          else
            echo "success=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}

      - name: Send Slack Message
        if: always()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
            "text": "create repo result ${{steps.create-repo.outcome}}",
            "attachments": [
                {
                "pretext": "create repo result ${{steps.create-repo.outcome}}",
                "color": "28a745",
                "fields": [
                    {
                    "title": "Status",
                    "short": true,
                    "value": "${{steps.create-repo.outcome}}"
                    }
                ]
                }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

        # run: |
        #   if [ "${{steps.create-repo.outputs.success}}" = "true" ]; then
        #     echo "Repository created successfully!" # Slack 메시지 전송 로직 추가
        #   else
        #     echo "Failed to create repository!" # 실패 알림 Slack 메시지 로직 추가
        #   fi
