name: auto-repository
on:
  workflow_dispatch:
    inputs:
      repository-name:
        required: true
        description: "레포지토리 input값 입력"

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository
        id: create-repository
        run: |
          gh repo create gpturtle-cicd-project/${{inputs.repository-nae}}-action-repo --public
          echo "success=true" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
      - name: Send Slack Message
        if: always()
        run: echo ${{steps.create-repository.outputs.success}}
