name: issue-messaging-lecture
on:
  issues:
    types: opened

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      issue-level: ${{ steps.get-keyword.outputs.level }}
    steps:
      - name: Checkout File
        uses: actions/checkout@v4

      - name: Get Keyword At File
        id: get-keyword
        run: |
          keywords=$(cat keyword-list.txt)
          level="Undefined"
          for keyword in $keywords; do
            if [[ "${{ github.event.issue.title }}" == *"$keyword"* ]]; then
              level="$keyword"
              break
            fi
          done
          echo "level=$level" >> $GITHUB_OUTPUT

      - name: Echo Keyword
        run: echo ${{ steps.get-keyword.outcome.level }}

  slack-message:
    runs-on: ubuntu-latest
    needs: get-keyword
    if: needs.get-keyword.outputs.issue-level != 'Undefined'
    environment: ${{ needs.get-keyword.outputs.issue-level }}
    steps:
      - name: Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "pretext": "issue alert message",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Level : ${{ needs.get-keyword.outputs.issue-level }}",
                      "short": true,
                      "value": "issue url: ${{ github.event.issue.html_url }}"
                    }
                  ]
                }
              ]
            }
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
