name: issue-messaging
on:
  issues:
    types: opened

jobs:
  issue-handling:
    runs-on: ubuntu-latest
    steps:
      - name: Handle Critical Issue
        id: slack-critical
        if: contains(github.event.issue.title, 'critical')
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
            "type": "actions",
            "block_id": "actions1",
            "elements": [
                {
                "type": "static_select",
                "placeholder":{
                    "type": "plain_text",
                    "text": "Which witch is the witchiest witch?"
                },
                "action_id": "select_2",
                "options": [
                    {
                    "text": {
                        "type": "plain_text",
                        "text": "Matilda"
                    },
                    "value": "matilda"
                    },
                    {
                    "text": {
                        "type": "plain_text",
                        "text": "Glinda"
                    },
                    "value": "glinda"
                    },
                    {
                    "text": {
                        "type": "plain_text",
                        "text": "Granny Weatherwax"
                    },
                    "value": "grannyWeatherwax"
                    },
                    {
                    "text": {
                        "type": "plain_text",
                        "text": "Hermione"
                    },
                    "value": "hermione"
                    }
                ]
                },
                {
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": "Cancel"
                },
                "value": "cancel",
                "action_id": "button_1"
                }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CRITICAL_ISSUE_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Handle Normal Issue
        id: slack-normal
        if: contains(github.event.issue.title, 'normal')
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
            "type": "actions",
            "block_id": "actions1",
            "elements": [
                {
                "type": "static_select",
                "placeholder":{
                    "type": "plain_text",
                    "text": "Which witch is the witchiest witch?"
                },
                "action_id": "select_2",
                "options": [
                    {
                    "text": {
                        "type": "plain_text",
                        "text": "Matilda"
                    },
                    "value": "matilda"
                    },
                    {
                    "text": {
                        "type": "plain_text",
                        "text": "Glinda"
                    },
                    "value": "glinda"
                    },
                    {
                    "text": {
                        "type": "plain_text",
                        "text": "Granny Weatherwax"
                    },
                    "value": "grannyWeatherwax"
                    },
                    {
                    "text": {
                        "type": "plain_text",
                        "text": "Hermione"
                    },
                    "value": "hermione"
                    }
                ]
                },
                {
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": "Cancel"
                },
                "value": "cancel",
                "action_id": "button_1"
                }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NORMAL_ISSUE_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
