name: issue-messaging-lecture
on:
  issues:
    types: opened

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      issue-level: ${{ steps.get-keyword.outputs.level }}
    steps:
      - name: Checkout File
        uses: actions/checkout@v4

      - name: Get Keyword At File
        id: get-keyword
        run: |
          keywords=$(cat keyword-list.txt)
          level="Undefined"
          for keyword in $keywords; do
            if [[ "${{ github.event.issue.title }}" == *"$keyword"* ]]; then
              level="$keyword"
              break
            fi
          done
          echo "level=$level" >> $GITHUB_OUTPUT

  print-keyword:
    runs-on: ubuntu-latest
    needs: get-keyword
    steps:
      - name: Print Keyword
        run: echo ${{ needs.get-keyword.outputs.issue-level }}
