name: issue-messaging
on:
  issues:
    types: opened

jobs:
  issue-handling:
    runs-on: ubuntu-latest
    steps:
      - name: Handle Critical Issue
        if: contains(github.event.issue.title, 'critical')
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "This is a section block with a button."
                        },
                        "accessory": {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "Click Me",
                                "emoji": true
                            },
                            "value": "click_me_123",
                            "action_id": "button-action"
                        }
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CRITICAL_ISSUE_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Handle Normal Issue
        if: contains(github.event.issue.title, 'normal')
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "This is a section block with a button."
                        },
                        "accessory": {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "Click Me",
                                "emoji": true
                            },
                            "value": "click_me_123",
                            "action_id": "button-action"
                        }
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NORMAL_ISSUE_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
