name: issue-messaging
on:
  issues:
    types: opened

jobs:
  issue-handling:
    runs-on: ubuntu-latest
    steps:
      - name: Handle Critical Issue
        if: contains(github.event.issue.title, 'critical')
        run: echo critical issue created.
      - name: Handle Normal Issue
        if: contains(github.event.issue.title, 'normal')
        run: echo normal issue created.
