name: issue-messaging-lecture
on: push
#   issues:
#     types: push

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      issue-level: ${{steps.get-keyword.outputs.level}}
    steps:
      - name: Get Keyword At File
        id: get-keyword
        run: echo "level=high" >> $GITHUB_OUTPUT
  print-keyword:
    runs-on: ubuntu-latest
    needs: get-keyword
    steps:
      - name: Print Keyword
        run: echo ${{needs.get-keyword.outputs.issue-level}}
