name: pull-request-workflow
on: pull_request

# 어떤 job들로 구성되어 있는지 표시
jobs:
  pull-request-job:
    # 실행시킬 runner 명시
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo hello world2
